<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <LangVersion>preview</LangVersion>
        <OutputType>Library</OutputType>
        <AssemblyName>TECS</AssemblyName>
        <RootNamespace>TECS</RootNamespace>
        <Authors>baginbix</Authors>
        <Description>A high-performance Sparse-Set ECS for .NET</Description>
        
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <AllowUnsafeBlocks>true</AllowUnsafeBlocks>

        <!-- MOVED HERE: These must be in a PropertyGroup -->
        <EmitCompilerGeneratedFiles>true</EmitCompilerGeneratedFiles>
        <CompilerGeneratedFilesOutputPath>GeneratedOutputs</CompilerGeneratedFilesOutputPath>
    </PropertyGroup>

    <ItemGroup>
        <Compile Remove="GeneratedOutputs\**" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\Generator\Generator.csproj" 
                        OutputItemType="Analyzer" 
                        ReferenceOutputAssembly="false" 
                        Pack="true"
                        PackagePath="analyzers/dotnet/cs"/>
    </ItemGroup>

    <ItemGroup>
        <InternalsVisibleTo Include="UnitTestsECS" />
    </ItemGroup>
</Project>