// <auto-generated/>
using System;
using System.Runtime.InteropServices;
using System.Runtime.CompilerServices;
using TECS;
using TECS.Query;

namespace TECS.Query
{

    public static class DoubleQueryExtensions
    {
        public static DoubleQueryEnumerator GetEnumerator(this TestQuery<DoubleQuery> query)
        {
            return new DoubleQueryEnumerator(query.World);
        }

            public static DoubleQuery Single(this TestQuery<DoubleQuery> query)
    {
        var enumerator = query.GetEnumerator();
        bool hasFirst = enumerator.MoveNext();
            #if DEBUG
            if (!hasFirst)
            {
                throw new InvalidCastException($"No DoubleQuery has been added.");
            }
            #endif
            Entity entity = enumerator.CurrentEntity;
            int idx0 = enumerator._idx0;
int idx1 = enumerator._idx1;

            #if DEBUG
            if (enumerator.MoveNext())
            {
                throw new InvalidOperationException($"More than one entity with queried component DoubleQuery has been found!");
            }
            #endif

            var _ecs = query.World;

                        var set0 = _ecs.GetSparseSet<TestComponent>();
            ref var dense0 = ref MemoryMarshal.GetReference(CollectionsMarshal.AsSpan(set0.GetDense()));
            var set1 = _ecs.GetSparseSet<TestComponent2>();
            ref var dense1 = ref MemoryMarshal.GetReference(CollectionsMarshal.AsSpan(set1.GetDense()));

            return new DoubleQuery{
                 entity = entity,
 comp1 = ref Unsafe.Add(ref dense0, idx0),
 comp2 = ref Unsafe.Add(ref dense1, idx1)

            };
    }

    }



    public ref struct DoubleQueryEnumerator
    {
        private readonly ECS _ecs;
        private ref Entity _entities;
        private ref TestComponent _dense0;
        private ref int[] _sparse0;
        internal int _idx0;
        private ref TestComponent2 _dense1;
        private ref int[] _sparse1;
        internal int _idx1;

        private readonly int _denseLength;
        private int _index;
        private int _indexDriver;

        public DoubleQueryEnumerator(ECS ecs)
        {
            _ecs = ecs;
            _index = -1;

            var set0 = _ecs.GetSparseSet<TestComponent>();
            _dense0 = ref MemoryMarshal.GetReference(CollectionsMarshal.AsSpan(set0.GetDense()));
            _sparse0 = ref MemoryMarshal.GetReference(set0.GetSparseSet());
            var set1 = _ecs.GetSparseSet<TestComponent2>();
            _dense1 = ref MemoryMarshal.GetReference(CollectionsMarshal.AsSpan(set1.GetDense()));
            _sparse1 = ref MemoryMarshal.GetReference(set1.GetSparseSet());

            if(set0.Size < set1.Size)
            {
                _indexDriver = 0;
                _entities  = ref MemoryMarshal.GetReference(CollectionsMarshal.AsSpan(set0.GetEntities()));
                _denseLength = set0.Size;
            }
            else
            {
                _indexDriver = 1;
                _entities = ref MemoryMarshal.GetReference(CollectionsMarshal.AsSpan(set1.GetEntities()));
                _denseLength = set1.Size;
            }

        }

        public bool MoveNext()
        {
            switch (_indexDriver) {
                case 0:
                    while(++_index < _denseLength) {
                        Entity entity = Unsafe.Add(ref _entities, _index);
                        int entityId = entity.Id;
                        int pageIndex = entityId >> 12; // Page shift
                        int pageOffset = entityId & 4095; // Page mask
                        if(pageIndex >= _sparse1.Length) continue;
                        int[] page1 = Unsafe.Add(ref _sparse1, pageIndex);
                        if(page1 == null) continue;

                        ref int pageData1 = ref MemoryMarshal.GetArrayDataReference(page1);
                        _idx1 = Unsafe.Add(ref pageData1, pageOffset);
                        if(_idx1 < 0) continue;
                        _idx0 = _index;
                        return true;
                    }
                    break;
                case 1:
                    while(++_index < _denseLength) {
                        Entity entity = Unsafe.Add(ref _entities, _index);
                        int entityId = entity.Id;
                        int pageIndex = entityId >> 12; // Page shift
                        int pageOffset = entityId & 4095; // Page mask
                        if(pageIndex >= _sparse0.Length) continue;
                        int[] page0 = Unsafe.Add(ref _sparse0, pageIndex);
                        if(page0 == null) continue;

                        ref int pageData0 = ref MemoryMarshal.GetArrayDataReference(page0);
                        _idx0 = Unsafe.Add(ref pageData0, pageOffset);
                        if(_idx0 < 0) continue;
                        _idx1 = _index;
                        return true;
                    }
                    break;
            }

            return false;
        }

        public DoubleQuery Current
        {
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            get
            {
                Entity entity = Unsafe.Add(ref _entities, _index);
                return new DoubleQuery
                {
                    entity = entity,
                    comp1 = ref Unsafe.Add(ref _dense0, _idx0),
                    comp2 = ref Unsafe.Add(ref _dense1, _idx1)

                };
            }
        }

        public Entity CurrentEntity{
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            get{
                return Unsafe.Add(ref _entities, _index);
            }
        }
    }

}