// <auto-generated/>
using System;
using System.Runtime.InteropServices;
using System.Runtime.CompilerServices;
using TECS;
using TECS.Query;

namespace TECS.Query
{

    public static class MyTestQueryExtensions
    {
        public static MyTestQueryEnumerator GetEnumerator(this TestQuery<MyTestQuery> query)
        {
            return new MyTestQueryEnumerator(query.World);
        }

            public static MyTestQuery Single(this TestQuery<MyTestQuery> query)
    {
        var enumerator = query.GetEnumerator();
        bool hasFirst = enumerator.MoveNext();
            #if DEBUG
            if (!hasFirst)
            {
                throw new InvalidCastException($"No MyTestQuery has been added.");
            }
            #endif
            Entity entity = enumerator.CurrentEntity;
            int idx0 = enumerator._idx0;

            #if DEBUG
            if (enumerator.MoveNext())
            {
                throw new InvalidOperationException($"More than one entity with queried component MyTestQuery has been found!");
            }
            #endif

            var _ecs = query.World;

                        var set0 = _ecs.GetSparseSet<TestComponent>();
            ref var dense0 = ref MemoryMarshal.GetReference(CollectionsMarshal.AsSpan(set0.GetDense()));

            return new MyTestQuery{
                 entity = entity,
 comp1 = ref Unsafe.Add(ref dense0, idx0)

            };
    }

    }



    public ref struct MyTestQueryEnumerator
    {
        private readonly ECS _ecs;
        private ref Entity _entities;
        private ref TestComponent _dense0;
        private ref int[] _sparse0;
        internal int _idx0;
        private readonly SparseSet<TestMarker> _with0;
        private readonly SparseSet<TestUnmarker> _without0;

        private readonly int _denseLength;
        private int _index;
        private int _indexDriver;

        public MyTestQueryEnumerator(ECS ecs)
        {
            _ecs = ecs;
            _index = -1;

            var set0 = _ecs.GetSparseSet<TestComponent>();
            _dense0 = ref MemoryMarshal.GetReference(CollectionsMarshal.AsSpan(set0.GetDense()));
            _sparse0 = ref MemoryMarshal.GetReference(set0.GetSparseSet());
            _with0 = _ecs.GetSparseSet<TestMarker>();
            _without0 = _ecs.GetSparseSet<TestUnmarker>();

            _entities = ref MemoryMarshal.GetReference(CollectionsMarshal.AsSpan(set0.GetEntities()));
            _denseLength = set0.Size;

        }

        public bool MoveNext()
        {
            switch (_indexDriver) {
                case 0:
                    while(++_index < _denseLength) {
                        Entity entity = Unsafe.Add(ref _entities, _index);
                        int entityId = entity.Id;
                        if (!_with0.Contains(entity)) continue;
                        if (_without0.Contains(entity)) continue;
                        _idx0 = _index;
                        return true;
                    }
                    break;
            }

            return false;
        }

        public MyTestQuery Current
        {
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            get
            {
                Entity entity = Unsafe.Add(ref _entities, _index);
                return new MyTestQuery
                {
                    entity = entity,
                    comp1 = ref Unsafe.Add(ref _dense0, _idx0)

                };
            }
        }

        public Entity CurrentEntity{
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            get{
                return Unsafe.Add(ref _entities, _index);
            }
        }
    }

}