// <auto-generated/>
using System;
using System.Runtime.InteropServices;
using System.Runtime.CompilerServices;
using TECS;
using TECS.Query;

namespace TECS.Query
{

    public static class TrippleQueryExtensions
    {
        public static TrippleQueryEnumerator GetEnumerator(this TestQuery<TrippleQuery> query)
        {
            return new TrippleQueryEnumerator(query.World);
        }

            public static TrippleQuery Single(this TestQuery<TrippleQuery> query)
    {
        var enumerator = query.GetEnumerator();
        bool hasFirst = enumerator.MoveNext();
            #if DEBUG
            if (!hasFirst)
            {
                throw new InvalidCastException($"No TrippleQuery has been added.");
            }
            #endif
            Entity entity = enumerator.CurrentEntity;
            int idx0 = enumerator._idx0;
int idx1 = enumerator._idx1;
int idx2 = enumerator._idx2;

            #if DEBUG
            if (enumerator.MoveNext())
            {
                throw new InvalidOperationException($"More than one entity with queried component TrippleQuery has been found!");
            }
            #endif

            var _ecs = query.World;

                        var set0 = _ecs.GetSparseSet<TestComponent>();
            ref var dense0 = ref MemoryMarshal.GetReference(CollectionsMarshal.AsSpan(set0.GetDense()));
            var set1 = _ecs.GetSparseSet<TestComponent2>();
            ref var dense1 = ref MemoryMarshal.GetReference(CollectionsMarshal.AsSpan(set1.GetDense()));
            var set2 = _ecs.GetSparseSet<TestComponent3>();
            ref var dense2 = ref MemoryMarshal.GetReference(CollectionsMarshal.AsSpan(set2.GetDense()));

            return new TrippleQuery{
                 comp1 = ref Unsafe.Add(ref dense0, idx0),
 comp2 = ref Unsafe.Add(ref dense1, idx1),
 comp3 = ref Unsafe.Add(ref dense2, idx2)

            };
    }

    }



    public ref struct TrippleQueryEnumerator
    {
        private readonly ECS _ecs;
        private ref Entity _entities;
        private ref TestComponent _dense0;
        private ref int[] _sparse0;
        internal int _idx0;
        private ref TestComponent2 _dense1;
        private ref int[] _sparse1;
        internal int _idx1;
        private ref TestComponent3 _dense2;
        private ref int[] _sparse2;
        internal int _idx2;
        private readonly SparseSet<TestMarker> _with0;

        private readonly int _denseLength;
        private int _index;
        private int _indexDriver;

        public TrippleQueryEnumerator(ECS ecs)
        {
            _ecs = ecs;
            _index = -1;

            var set0 = _ecs.GetSparseSet<TestComponent>();
            _dense0 = ref MemoryMarshal.GetReference(CollectionsMarshal.AsSpan(set0.GetDense()));
            _sparse0 = ref MemoryMarshal.GetReference(set0.GetSparseSet());
            var set1 = _ecs.GetSparseSet<TestComponent2>();
            _dense1 = ref MemoryMarshal.GetReference(CollectionsMarshal.AsSpan(set1.GetDense()));
            _sparse1 = ref MemoryMarshal.GetReference(set1.GetSparseSet());
            var set2 = _ecs.GetSparseSet<TestComponent3>();
            _dense2 = ref MemoryMarshal.GetReference(CollectionsMarshal.AsSpan(set2.GetDense()));
            _sparse2 = ref MemoryMarshal.GetReference(set2.GetSparseSet());
            _with0 = _ecs.GetSparseSet<TestMarker>();

            if(set0.Size < set1.Size && set0.Size < set2.Size)
            {
                _indexDriver = 0;
                _entities  = ref MemoryMarshal.GetReference(CollectionsMarshal.AsSpan(set0.GetEntities()));
                _denseLength = set0.Size;
            }
            else if(set1.Size < set2.Size)
            {
                _indexDriver = 1;
                _entities  = ref MemoryMarshal.GetReference(CollectionsMarshal.AsSpan(set1.GetEntities()));
                _denseLength = set1.Size;
            }
            else
            {
                _indexDriver = 2;
                _entities = ref MemoryMarshal.GetReference(CollectionsMarshal.AsSpan(set2.GetEntities()));
                _denseLength = set2.Size;
            }

        }

        public bool MoveNext()
        {
            switch (_indexDriver) {
                case 0:
                    while(++_index < _denseLength) {
                        Entity entity = Unsafe.Add(ref _entities, _index);
                        int entityId = entity.Id;
                        int pageIndex = entityId >> 12; // Page shift
                        int pageOffset = entityId & 4095; // Page mask
                        if (!_with0.Contains(entity)) continue;
                        if(pageIndex >= _sparse1.Length) continue;
                        int[] page1 = Unsafe.Add(ref _sparse1, pageIndex);
                        if(page1 == null) continue;

                        ref int pageData1 = ref MemoryMarshal.GetArrayDataReference(page1);
                        _idx1 = Unsafe.Add(ref pageData1, pageOffset);
                        if(_idx1 < 0) continue;
                        if(pageIndex >= _sparse2.Length) continue;
                        int[] page2 = Unsafe.Add(ref _sparse2, pageIndex);
                        if(page2 == null) continue;

                        ref int pageData2 = ref MemoryMarshal.GetArrayDataReference(page2);
                        _idx2 = Unsafe.Add(ref pageData2, pageOffset);
                        if(_idx2 < 0) continue;
                        _idx0 = _index;
                        return true;
                    }
                    break;
                case 1:
                    while(++_index < _denseLength) {
                        Entity entity = Unsafe.Add(ref _entities, _index);
                        int entityId = entity.Id;
                        int pageIndex = entityId >> 12; // Page shift
                        int pageOffset = entityId & 4095; // Page mask
                        if (!_with0.Contains(entity)) continue;
                        if(pageIndex >= _sparse0.Length) continue;
                        int[] page0 = Unsafe.Add(ref _sparse0, pageIndex);
                        if(page0 == null) continue;

                        ref int pageData0 = ref MemoryMarshal.GetArrayDataReference(page0);
                        _idx0 = Unsafe.Add(ref pageData0, pageOffset);
                        if(_idx0 < 0) continue;
                        if(pageIndex >= _sparse2.Length) continue;
                        int[] page2 = Unsafe.Add(ref _sparse2, pageIndex);
                        if(page2 == null) continue;

                        ref int pageData2 = ref MemoryMarshal.GetArrayDataReference(page2);
                        _idx2 = Unsafe.Add(ref pageData2, pageOffset);
                        if(_idx2 < 0) continue;
                        _idx1 = _index;
                        return true;
                    }
                    break;
                case 2:
                    while(++_index < _denseLength) {
                        Entity entity = Unsafe.Add(ref _entities, _index);
                        int entityId = entity.Id;
                        int pageIndex = entityId >> 12; // Page shift
                        int pageOffset = entityId & 4095; // Page mask
                        if (!_with0.Contains(entity)) continue;
                        if(pageIndex >= _sparse0.Length) continue;
                        int[] page0 = Unsafe.Add(ref _sparse0, pageIndex);
                        if(page0 == null) continue;

                        ref int pageData0 = ref MemoryMarshal.GetArrayDataReference(page0);
                        _idx0 = Unsafe.Add(ref pageData0, pageOffset);
                        if(_idx0 < 0) continue;
                        if(pageIndex >= _sparse1.Length) continue;
                        int[] page1 = Unsafe.Add(ref _sparse1, pageIndex);
                        if(page1 == null) continue;

                        ref int pageData1 = ref MemoryMarshal.GetArrayDataReference(page1);
                        _idx1 = Unsafe.Add(ref pageData1, pageOffset);
                        if(_idx1 < 0) continue;
                        _idx2 = _index;
                        return true;
                    }
                    break;
            }

            return false;
        }

        public TrippleQuery Current
        {
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            get
            {
                Entity entity = Unsafe.Add(ref _entities, _index);
                return new TrippleQuery
                {
                    comp1 = ref Unsafe.Add(ref _dense0, _idx0),
                    comp2 = ref Unsafe.Add(ref _dense1, _idx1),
                    comp3 = ref Unsafe.Add(ref _dense2, _idx2)

                };
            }
        }

        public Entity CurrentEntity{
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            get{
                return Unsafe.Add(ref _entities, _index);
            }
        }
    }

}