using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using System.Security.Cryptography.X509Certificates;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace TECS.Generators;


[Generator(LanguageNames.CSharp)]
public class SystemRegistrationGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        // Find all methods tagged with [System] using the exact metadata name
        var systemMethods = context.SyntaxProvider
        .ForAttributeWithMetadataName(
            fullyQualifiedMetadataName: "TECS.SystemAttribute",
            // 1. Fast filter: only look at attributes attached to methods
            predicate: static (node, cancellationToken) => node is MethodDeclarationSyntax,
            // 2. Transform: extract the semantic symbol
            transform: static (syntaxContext, cancellationToken) => (IMethodSymbol)syntaxContext.TargetSymbol
        )
        // 3. Final filter: ensure it's static and returns void
        .Where(symbol => symbol.IsStatic && symbol.ReturnsVoid);

        context.RegisterSourceOutput(systemMethods.Collect(), GenerateSystemBoilerplate);
    }

    private static void GenerateSystemBoilerplate(SourceProductionContext context, ImmutableArray<IMethodSymbol> methods)
    {
        if (methods.IsDefaultOrEmpty) return;

        var sourceBuilder = new StringBuilder();
        sourceBuilder.AppendLine("// <auto-generated />");
        sourceBuilder.AppendLine("using System;");
        sourceBuilder.AppendLine("using TECS;");
        sourceBuilder.AppendLine("using TECS.Event;");
        sourceBuilder.AppendLine("using TECS.Query;");
        sourceBuilder.AppendLine("using TECS.Commands;");
        sourceBuilder.AppendLine("using TECS.Systems;");
        sourceBuilder.AppendLine();
        sourceBuilder.AppendLine("namespace TECS");
        sourceBuilder.AppendLine("{");

        var generatedSignatures = new HashSet<string>();
        var delegatesAndBindingsBuilder = new StringBuilder();

        // Start the extension class
        sourceBuilder.AppendLine("    public static class AppExtensions");
        sourceBuilder.AppendLine("    {");

        foreach (var method in methods)
        {
            List<(string Sig,string Id,string Arg, string Setup)> queryTypes = new();
            // Extract the generic arguments of any Query<T> parameters
            foreach(var param in method.Parameters)
            {
                var t = param.Type as INamedTypeSymbol;
                if(t == null) continue;

                if(t.Name == "Query" && t.TypeArguments.Length == 1)
                {
                    var qType = t.TypeArguments[0].ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);

                    queryTypes.Add( new (
                        $"Query<{qType}>",
                        qType.Replace("global::", "").Replace(".", "_"),
                        $"new Query<{qType}>(ecs)",
                        null
                    ));
                }
                
                else if (t.Name == "CommandBuffer")
                {
                    queryTypes.Add( new (
                       "CommandBuffer",
                        "CommandBuffer",
                        "cmd", // Pass the exact variable from the Run method,
                        null
                    ));
                }
                else if(t.Name == "EventWriter" && t.TypeArguments.Length == 1 )
                {
                    var qType = t.TypeArguments[0].ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
                    string argName = $"writer_{queryTypes.Count}";
                    queryTypes.Add( new (
                        $"EventWriter<{qType}>",
                        qType.Replace("global::", "").Replace(".", "_") + "Write",
                        argName,
                        $"var {argName} = ecs.GetEventWriter<{qType}>();"
                        
                    ));
                }
                else if(t.Name == "EventReader" && t.TypeArguments.Length == 1 )
                {
                    var qType = t.TypeArguments[0].ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
                     string argName = $"writer_{queryTypes.Count}";
                    queryTypes.Add( new (
                        $"EventReader<{qType}>",
                        qType.Replace("global::", "").Replace(".", "_") + "Read" ,
                        argName,
                        $"var {argName} = ecs.GetEventReader<{qType}>();"
                    ));
                }
                else if (t.Name == "Res" && t.TypeArguments.Length == 1)
{
                    var resType = t.TypeArguments[0].ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
                    string argName = $"res_{queryTypes.Count}";
                    queryTypes.Add((
                        $"Res<{resType}>",
                        resType.Replace("global::", "").Replace(".", "_") + "_Res",
                        argName,
                        $" var {argName} = new global::TECS.Query.Res<{resType}> {{ Value = ecs.GetResource<{resType}>() }};"
                ));
}

            }
            /*
            var queryTypes = method.Parameters
                .Select(p => p.Type as INamedTypeSymbol)
                .Where(t => t != null )
                .Select(t =>{
                    if(t.Name == "Query" && t.TypeArguments.Length == 1)
                    {
                        var qType = t.TypeArguments[0].ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
                        return new {
                            Sig = $"Query<{qType}>",
                            Id = qType.Replace("global::", "").Replace(".", "_"),
                            Arg = $"new Query<{qType}>(ecs)"
                        };
                    }
                    
                    if (t.Name == "CommandBuffer")
                    {
                        return new {
                            Sig = "CommandBuffer",
                            Id = "CommandBuffer",
                            Arg = "cmd" // Pass the exact variable from the Run method
                        };
                    }
                    if(t.Name == "EventWriter" && t.TypeArguments.Length == 1 )
                    {
                        var qType = t.TypeArguments[0].ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
                        return new {
                            Sig = $"Query<{qType}>",
                            Id = qType.Replace("global::", "").Replace(".", "_"),
                            Arg = $"new Query<{qType}>(ecs)"
                        };
                    }
                    return null;

                })
                .Where(x => x is not null)
                .ToList();
            */
            if (queryTypes.Count == 0) continue;

            // Create a safe, unique string based on the query types 
            // e.g., "global__MyQuery_global__TrippleQuery"
            string uniqueId = string.Join("_", queryTypes.Select(q => q.Id));
            // Only generate the boilerplate once per unique parameter combination
            if (generatedSignatures.Add(uniqueId))
            {
               // Generate Extension Method for App
                sourceBuilder.AppendLine($"        public static App AddSystem(this App app, SystemDelegate_{uniqueId} system, SystemPhase phase = SystemPhase.Update)");
                sourceBuilder.AppendLine("        {");
                sourceBuilder.AppendLine($"            app.AddSystemBinding(new SystemBinding_{uniqueId}(system), phase);"); // <-- NEW (Safe!)
                sourceBuilder.AppendLine("            return app;");
                sourceBuilder.AppendLine("        }");
                sourceBuilder.AppendLine();

                // Generate AddSystemOnEnter
                sourceBuilder.AppendLine($"        public static App AddSystemOnEnter<TState>(this App app, TState state, SystemDelegate_{uniqueId} system) where TState : struct, Enum");
                sourceBuilder.AppendLine("        {");
                sourceBuilder.AppendLine($"            app.AddSystemOnEnter(state, new SystemBinding_{uniqueId}(system));"); // <-- NEW (Safe!)
                sourceBuilder.AppendLine("            return app;");
                sourceBuilder.AppendLine("        }");
                sourceBuilder.AppendLine();

                // Generate AddSystemOnUpdate
                sourceBuilder.AppendLine($"        public static App AddSystemOnUpdate<TState>(this App app, TState state, SystemDelegate_{uniqueId} system) where TState : struct, Enum");
                sourceBuilder.AppendLine("        {");
                sourceBuilder.AppendLine($"            app.AddSystemOnUpdate(state, new SystemBinding_{uniqueId}(system));"); // <-- NEW (Safe!)
                sourceBuilder.AppendLine("            return app;");
                sourceBuilder.AppendLine("        }");
                sourceBuilder.AppendLine();

                // Generate AddSystemOnExit
                sourceBuilder.AppendLine($"        public static App AddSystemOnExit<TState>(this App app, TState state, SystemDelegate_{uniqueId} system) where TState : struct, Enum");
                sourceBuilder.AppendLine("        {");
                sourceBuilder.AppendLine($"            app.AddSystemOnExit(state, new SystemBinding_{uniqueId}(system));");
                sourceBuilder.AppendLine("            return app;");
                sourceBuilder.AppendLine("        }");
                sourceBuilder.AppendLine();

                // Generate Custom Delegate (stored in the secondary builder)

                string typeParams = string.Join(", ", queryTypes.Select((p, i) => $"{p.Sig} p{i}"));
                delegatesAndBindingsBuilder.AppendLine($"    public delegate void SystemDelegate_{uniqueId}({typeParams});");
                
                // Generate System Binding
                delegatesAndBindingsBuilder.AppendLine($"    public class SystemBinding_{uniqueId} : SystemBinding");
                delegatesAndBindingsBuilder.AppendLine("    {");
                delegatesAndBindingsBuilder.AppendLine($"        private readonly SystemDelegate_{uniqueId} _func;");
                
                var bindingCtorBuilder = new StringBuilder();
                if(queryTypes.Count > 0)
                {
                    // System has 1 or more queries
                    bindingCtorBuilder.AppendLine("                List<Type> readsList = new List<Type>();");
                    bindingCtorBuilder.AppendLine("                List<Type> writesList = new List<Type>();");
                    
                    foreach (var q in queryTypes)
                    {
                        string fullExtensionPath = "global::" + q.Id.Replace('_', '.') + "Extensions";
                        string extName = $"{q.Id.Split('_').Last()}Extensions";
                        if(q.Sig != "CommandBuffer")
                        {
                            bindingCtorBuilder.AppendLine($"                readsList.AddRange({fullExtensionPath}.GetReads);");
                            bindingCtorBuilder.AppendLine($"                writesList.AddRange({fullExtensionPath}.GetWrites);");   
                        }
                    }

                    bindingCtorBuilder.AppendLine("                Reads = readsList.ToArray();");
                    bindingCtorBuilder.AppendLine("                Writes = writesList.ToArray();");
                }
                else
                {
                    // System only takes CommandBuffer / ECS (e.g. Startup Systems)
                    bindingCtorBuilder.AppendLine("                Reads = Array.Empty<Type>();");
                    bindingCtorBuilder.AppendLine("                Writes = Array.Empty<Type>();");
                }
                delegatesAndBindingsBuilder.AppendLine($$"""        
            public SystemBinding_{{uniqueId}}(SystemDelegate_{{uniqueId}} func){
                _func = func;
                {{bindingCtorBuilder}}
            }
            """);
                
                string setup = string.Join("\n                        ", queryTypes.Select(p => p.Setup));

                string instantiationParams = string.Join(", ", queryTypes.Select(q => q.Arg));
                delegatesAndBindingsBuilder.AppendLine($$"""        
                    public override void Run(ECS ecs , CommandBuffer cmd)
                    {
                        {{setup}}
                        _func({{instantiationParams}});
                        
                    }
                """);
                delegatesAndBindingsBuilder.AppendLine("    }");
                delegatesAndBindingsBuilder.AppendLine();
            }
        }

        // Close extension class
        sourceBuilder.AppendLine("    }");
        sourceBuilder.AppendLine();
        
        // Append all the generated delegates and classes
        sourceBuilder.Append(delegatesAndBindingsBuilder.ToString());
        
        // Close namespace
        sourceBuilder.AppendLine("}");

        context.AddSource("AppSystemExtensions.g.cs", sourceBuilder.ToString());
    }
}