using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using System.Text;
using Generator;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace TECS.Generators;

[Generator(LanguageNames.CSharp)]
public class SystemRegistrationGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var systemMethods = context
            .SyntaxProvider.ForAttributeWithMetadataName(
                fullyQualifiedMetadataName: "TECS.SystemAttribute",
                predicate: static (node, _) => node is MethodDeclarationSyntax,
                transform: static (syntaxContext, _) => (IMethodSymbol)syntaxContext.TargetSymbol
            )
            .Where(symbol => symbol.IsStatic && symbol.ReturnsVoid);

        context.RegisterSourceOutput(systemMethods.Collect(), GenerateSystemBoilerplate);
    }

    private static void GenerateSystemBoilerplate(
        SourceProductionContext context,
        ImmutableArray<IMethodSymbol> methods
    )
    {
        if (methods.IsDefaultOrEmpty)
            return;

        var sourceBuilder = new StringBuilder();
        sourceBuilder.AppendLine(
            """
            // <auto-generated />
            using System;
            using TECS;
            using TECS.Event;
            using TECS.Query;
            using TECS.Commands;
            using TECS.Systems;
            using TECS.Resources;

            namespace TECS
            {
                public static class AppExtensions
                {
            """
        );

        var generatedSignatures = new HashSet<string>();
        var delegatesAndBindingsBuilder = new StringBuilder();

        foreach (var method in methods)
        {
            var parameters = method
                .Parameters.Select((p, i) => ParseSystem(p, i))
                .Where(p => p is not null)
                .ToList()!;

            if (parameters.Count == 0)
                continue;

            // Generate unique signature identifier based on parameter TYPES (e.g. Query_Pos_Res_Time)
            string uniqueId = string.Join("_", parameters.Select(q => q.TypeSignatureId));

            // Generate extensions once per unique parameter combination
            if (generatedSignatures.Add(uniqueId))
            {
                // 1. Generate App Extension Methods
                sourceBuilder.AppendLine(
                    $$"""
                            public static App AddSystem(this App app, SystemDelegate_{{uniqueId}} system, SystemPhase phase = SystemPhase.Update)
                            {
                                app.AddSystemBinding(new SystemBinding_{{uniqueId}}(system), phase);
                                return app;
                            }

                            public static App AddSystemOnEnter<TState>(this App app, TState state, SystemDelegate_{{uniqueId}} system) where TState : struct, Enum
                            {
                                app.AddSystemOnEnter(state, new SystemBinding_{{uniqueId}}(system));
                                return app;
                            }

                            public static App AddSystemOnUpdate<TState>(this App app, TState state, SystemDelegate_{{uniqueId}} system) where TState : struct, Enum
                            {
                                app.AddSystemOnUpdate(state, new SystemBinding_{{uniqueId}}(system));
                                return app;
                            }

                            public static App AddSystemOnExit<TState>(this App app, TState state, SystemDelegate_{{uniqueId}} system) where TState : struct, Enum
                            {
                                app.AddSystemOnExit(state, new SystemBinding_{{uniqueId}}(system));
                                return app;
                            }
                    """
                );

                // 2. Delegate Signature
                string delegateParams = string.Join(
                    ", ",
                    parameters.Select((p, i) => $"{p.FullTypeName} p{i}")
                );

                // 3. Reads / Writes DAG Code
                var reads = parameters.Select(p => p.GetReadsCode()).Where(c => c != null).ToList();
                var writes = parameters
                    .Select(p => p.GetWritesCode())
                    .Where(c => c != null)
                    .ToList();

                StringBuilder readsWritesBuilder = new StringBuilder();
                if (reads.Count > 0 || writes.Count > 0)
                {
                    readsWritesBuilder.AppendLine("List<Type> readsList = new List<Type>();");
                    readsWritesBuilder.AppendLine(
                        "                List<Type> writesList = new List<Type>();"
                    );
                    foreach (var r in reads)
                        readsWritesBuilder.AppendLine($"                {r}");
                    foreach (var w in writes)
                        readsWritesBuilder.AppendLine($"                {w}");
                    readsWritesBuilder.AppendLine("                Reads = readsList.ToArray();");
                    readsWritesBuilder.AppendLine("                Writes = writesList.ToArray();");
                }
                else
                {
                    readsWritesBuilder.AppendLine("Reads = Array.Empty<Type>();");
                    readsWritesBuilder.AppendLine("                Writes = Array.Empty<Type>();");
                }

                // 4. Setup Statements & Invocations
                string setupStatements = string.Join(
                    "\n                        ",
                    parameters
                        .Select(p => p.GenerateSetupCode())
                        .Where(c => !string.IsNullOrEmpty(c))
                );

                string callArguments = string.Join(
                    ", ",
                    parameters.Select(p => p.GenerateArgumentCode())
                );

                // 5. Append Delegate & Binding Definition
                delegatesAndBindingsBuilder.AppendLine(
                    $$"""
                        public delegate void SystemDelegate_{{uniqueId}}({{delegateParams}});

                        public class SystemBinding_{{uniqueId}} : SystemBinding
                        {
                            private readonly SystemDelegate_{{uniqueId}} _func;

                            public SystemBinding_{{uniqueId}}(SystemDelegate_{{uniqueId}} func)
                            {
                                _func = func;
                                {{readsWritesBuilder.ToString().TrimEnd()}}
                            }

                            public override void Run(ECS ecs, CommandBuffer cmd, uint systemTick)
                            {
                                {{setupStatements}}
                                _func({{callArguments}});
                            }
                        }

                    """
                );
            }
        }

        // Close AppExtensions class
        sourceBuilder.AppendLine("    }");
        sourceBuilder.AppendLine();

        // Append generated delegates and binding classes
        sourceBuilder.Append(delegatesAndBindingsBuilder.ToString());

        // Close TECS namespace
        sourceBuilder.AppendLine("}");

        context.AddSource("AppSystemExtensions.g.cs", sourceBuilder.ToString());
    }

    private static SystemParam? ParseSystem(IParameterSymbol param, int index)
    {
        if (param.Type is not INamedTypeSymbol t)
            return null;

        string paramName = param.Name;

        if (t.Name == "Query" && t.TypeArguments.Length == 1)
        {
            string queryStruct = t.TypeArguments[0]
                .ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
            return new QueryParam(paramName, index, queryStruct);
        }
        if (t.Name == "CommandBuffer")
        {
            return new CommandBufferParam(paramName, index);
        }
        if (t.Name == "EventReader" && t.TypeArguments.Length == 1)
        {
            string eventType = t.TypeArguments[0]
                .ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
            return new EventReaderParam(paramName, index, eventType);
        }
        if (t.Name == "EventWriter" && t.TypeArguments.Length == 1)
        {
            string eventType = t.TypeArguments[0]
                .ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
            return new EventWriterParam(paramName, index, eventType);
        }
        if (t.Name == "Res" && t.TypeArguments.Length == 1)
        {
            string resType = t.TypeArguments[0]
                .ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
            return new ResParam(paramName, index, resType);
        }
        if (t.Name == "ResMut" && t.TypeArguments.Length == 1)
        {
            string resType = t.TypeArguments[0]
                .ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
            return new ResMutParam(paramName, index, resType);
        }

        return null;
    }
}
